# Generated by Django 5.0.2 on 2024-03-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssl_info',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssl_info',
            name='skill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
