export const currency = [
  { value: 'AED - United Arab Emirates Dirham (د.إ)', label: 'AED (د.إ)' },
  { value: 'AFN - Afghan Afghani (؋)', label: 'AFN (؋)' },
  { value: 'ALL - Albanian Lek (Lek)', label: 'ALL (Lek)' },
  { value: 'AMD - Armenian Dram (֏)', label: 'AMD (֏)' },
  { value: 'ANG - Netherlands Antillean Guilder (ƒ)', label: 'ANG (ƒ)' },
  { value: 'AOA - Angolan Kwanza (Kz)', label: 'AOA (Kz)' },
  { value: 'ARS - Argentine Peso ($)', label: 'ARS ($)' },
  { value: 'AUD - Australian Dollar ($)', label: 'AUD ($)' },
  { value: 'AWG - Aruban Florin (ƒ)', label: 'AWG (ƒ)' },
  { value: 'AZN - Azerbaijani Manat (₼)', label: 'AZN (₼)' },
  {
    value: 'BAM - Bosnia-Herzegovina Convertible Mark (KM)',
    label: 'BAM (KM)',
  },
  { value: 'BBD - Barbadian Dollar ($)', label: 'BBD ($)' },
  { value: 'BDT - Bangladeshi Taka (৳)', label: 'BDT (৳)' },
  { value: 'BGN - Bulgarian Lev (лв)', label: 'BGN (лв)' },
  { value: 'BHD - Bahraini Dinar (ب.د)', label: 'BHD (ب.د)' },
  { value: 'BIF - Burundian Franc (FBu)', label: 'BIF (FBu)' },
  { value: 'BMD - Bermudian Dollar ($)', label: 'BMD ($)' },
  { value: 'BND - Brunei Dollar ($)', label: 'BND ($)' },
  { value: 'BOB - Bolivian Boliviano (Bs.)', label: 'BOB (Bs.)' },
  { value: 'BRL - Brazilian Real (R$)', label: 'BRL (R$)' },
  { value: 'BSD - Bahamian Dollar ($)', label: 'BSD ($)' },
  { value: 'BTN - Bhutanese Ngultrum (Nu.)', label: 'BTN (Nu.)' },
  { value: 'BWP - Botswanan Pula (P)', label: 'BWP (P)' },
  { value: 'BYN - Belarusian Ruble (Br)', label: 'BYN (Br)' },
  { value: 'BZD - Belize Dollar (BZ$)', label: 'BZD (BZ$)' },
  { value: 'CAD - Canadian Dollar ($)', label: 'CAD ($)' },
  { value: 'CDF - Congolese Franc (FC)', label: 'CDF (FC)' },
  { value: 'CHF - Swiss Franc (Fr.)', label: 'CHF (Fr.)' },
  { value: 'CLP - Chilean Peso ($)', label: 'CLP ($)' },
  { value: 'CNY - Chinese Yuan (¥)', label: 'CNY (¥)' },
  { value: 'COP - Colombian Peso ($)', label: 'COP ($)' },
  { value: 'CRC - Costa Rican Colón (₡)', label: 'CRC (₡)' },
  { value: 'CUP - Cuban Peso (₱)', label: 'CUP (₱)' },
  { value: 'CVE - Cape Verdean Escudo (Esc)', label: 'CVE (Esc)' },
  { value: 'CZK - Czech Republic Koruna (Kč)', label: 'CZK (Kč)' },
  { value: 'DJF - Djiboutian Franc (Fdj)', label: 'DJF (Fdj)' },
  { value: 'DKK - Danish Krone (kr)', label: 'DKK (kr)' },
  { value: 'DOP - Dominican Peso (RD$)', label: 'DOP (RD$)' },
  { value: 'DZD - Algerian Dinar (د.ج)', label: 'DZD (د.ج)' },
  { value: 'EGP - Egyptian Pound (£)', label: 'EGP (£)' },
  { value: 'ERN - Eritrean Nakfa (Nfk)', label: 'ERN (Nfk)' },
  { value: 'ETB - Ethiopian Birr (Br)', label: 'ETB (Br)' },
  { value: 'EUR - Euro (€)', label: 'EUR (€)' },
  { value: 'FJD - Fijian Dollar ($)', label: 'FJD ($)' },
  { value: 'FKP - Falkland Islands Pound (£)', label: 'FKP (£)' },
  { value: 'GBP - British Pound Sterling (£)', label: 'GBP (£)' },
  { value: 'GEL - Georgian Lari (₾)', label: 'GEL (₾)' },
  { value: 'GGP - Guernsey Pound (£)', label: 'GGP (£)' },
  { value: 'GHS - Ghanaian Cedi (₵)', label: 'GHS (₵)' },
  { value: 'GIP - Gibraltar Pound (£)', label: 'GIP (£)' },
  { value: 'GMD - Gambian Dalasi (D)', label: 'GMD (D)' },
  { value: 'GNF - Guinean Franc (FG)', label: 'GNF (FG)' },
  { value: 'GTQ - Guatemalan Quetzal (Q)', label: 'GTQ (Q)' },
  { value: 'GYD - Guyanaese Dollar ($)', label: 'GYD ($)' },
  { value: 'HKD - Hong Kong Dollar (HK$)', label: 'HKD (HK$)' },
  { value: 'HNL - Honduran Lempira (L)', label: 'HNL (L)' },
  { value: 'HRK - Croatian Kuna (kn)', label: 'HRK (kn)' },
  { value: 'HTG - Haitian Gourde (G)', label: 'HTG (G)' },
  { value: 'HUF - Hungarian Forint (Ft)', label: 'HUF (Ft)' },
  { value: 'IDR - Indonesian Rupiah (Rp)', label: 'IDR (Rp)' },
  { value: 'ILS - Israeli New Sheqel (₪)', label: 'ILS (₪)' },
  { value: 'IMP - Isle of Man Pound (£)', label: 'IMP (£)' },
  { value: 'INR - Indian Rupee (₹)', label: 'INR (₹)' },
  { value: 'IQD - Iraqi Dinar (د.ع)', label: 'IQD (د.ع)' },
  { value: 'IRR - Iranian Rial (﷼)', label: 'IRR (﷼)' },
  { value: 'ISK - Icelandic Króna (kr)', label: 'ISK (kr)' },
  { value: 'JEP - Jersey Pound (£)', label: 'JEP (£)' },
  { value: 'JMD - Jamaican Dollar (J$)', label: 'JMD (J$)' },
  { value: 'JOD - Jordanian Dinar (د.ا)', label: 'JOD (د.ا)' },
  { value: 'JPY - Japanese Yen (¥)', label: 'JPY (¥)' },
  { value: 'KES - Kenyan Shilling (KSh)', label: 'KES (KSh)' },
  { value: 'KGS - Kyrgystani Som (сом)', label: 'KGS (сом)' },
  { value: 'KHR - Cambodian Riel (៛)', label: 'KHR (៛)' },
  { value: 'KMF - Comorian Franc (CF)', label: 'KMF (CF)' },
  { value: 'KRW - South Korean Won (₩)', label: 'KRW (₩)' },
  { value: 'KWD - Kuwaiti Dinar (د.ك)', label: 'KWD (د.ك)' },
  { value: 'KYD - Cayman Islands Dollar ($)', label: 'KYD ($)' },
  { value: 'KZT - Kazakhstani Tenge (₸)', label: 'KZT (₸)' },
  { value: 'LAK - Laotian Kip (₭)', label: 'LAK (₭)' },
  { value: 'LBP - Lebanese Pound (£)', label: 'LBP (£)' },
  { value: 'LKR - Sri Lankan Rupee (₨)', label: 'LKR (₨)' },
  { value: 'LRD - Liberian Dollar ($)', label: 'LRD ($)' },
  { value: 'LSL - Lesotho Loti (L)', label: 'LSL (L)' },
  { value: 'LYD - Libyan Dinar (ل.د)', label: 'LYD (ل.د)' },
  { value: 'MAD - Moroccan Dirham (د.م.)', label: 'MAD (د.م.)' },
  { value: 'MDL - Moldovan Leu (L)', label: 'MDL (L)' },
  { value: 'MGA - Malagasy Ariary (Ar)', label: 'MGA (Ar)' },
  { value: 'MKD - Macedonian Denar (ден)', label: 'MKD (ден)' },
  { value: 'MMK - Myanma Kyat (Ks)', label: 'MMK (Ks)' },
  { value: 'MNT - Mongolian Tugrik (₮)', label: 'MNT (₮)' },
  { value: 'MOP - Macanese Pataca (MOP$)', label: 'MOP (MOP$)' },
  { value: 'MUR - Mauritian Rupee (₨)', label: 'MUR (₨)' },
  { value: 'MVR - Maldivian Rufiyaa (Rf)', label: 'MVR (Rf)' },
  { value: 'MWK - Malawian Kwacha (MK)', label: 'MWK (MK)' },
  { value: 'MXN - Mexican Peso ($)', label: 'MXN ($)' },
  { value: 'MYR - Malaysian Ringgit (RM)', label: 'MYR (RM)' },
  { value: 'MZN - Mozambican Metical (MT)', label: 'MZN (MT)' },
  { value: 'NAD - Namibian Dollar (N$)', label: 'NAD (N$)' },
  { value: 'NGN - Nigerian Naira (₦)', label: 'NGN (₦)' },
  { value: 'NIO - Nicaraguan Córdoba (C$)', label: 'NIO (C$)' },
  { value: 'NOK - Norwegian Krone (kr)', label: 'NOK (kr)' },
  { value: 'NPR - Nepalese Rupee (₨)', label: 'NPR (₨)' },
  { value: 'NZD - New Zealand Dollar ($)', label: 'NZD ($)' },
  { value: 'OMR - Omani Rial (ر.ع.)', label: 'OMR (ر.ع.)' },
  { value: 'PAB - Panamanian Balboa (B/.)', label: 'PAB (B/.)' },
  { value: 'PEN - Peruvian Nuevo Sol (S/.)', label: 'PEN (S/.)' },
  { value: 'PGK - Papua New Guinean Kina (K)', label: 'PGK (K)' },
  { value: 'PHP - Philippine Peso (₱)', label: 'PHP (₱)' },
  { value: 'PKR - Pakistani Rupee (₨)', label: 'PKR (₨)' },
  { value: 'PLN - Polish Zloty (zł)', label: 'PLN (zł)' },
  { value: 'PYG - Paraguayan Guarani (₲)', label: 'PYG (₲)' },
  { value: 'QAR - Qatari Rial (ر.ق)', label: 'QAR (ر.ق)' },
  { value: 'RON - Romanian Leu (lei)', label: 'RON (lei)' },
  { value: 'RSD - Serbian Dinar (дин.)', label: 'RSD (дин.)' },
  { value: 'RUB - Russian Ruble (₽)', label: 'RUB (₽)' },
  { value: 'RWF - Rwandan Franc (FRw)', label: 'RWF (FRw)' },
  { value: 'SAR - Saudi Riyal (ر.س)', label: 'SAR (ر.س)' },
  { value: 'SBD - Solomon Islands Dollar (SI$)', label: 'SBD (SI$)' },
  { value: 'SCR - Seychellois Rupee (₨)', label: 'SCR (₨)' },
  { value: 'SEK - Swedish Krona (kr)', label: 'SEK (kr)' },
  { value: 'SGD - Singapore Dollar ($)', label: 'SGD ($)' },
  { value: 'SHP - Saint Helena Pound (£)', label: 'SHP (£)' },
  { value: 'SLE - Sierra Leonean Leone (Le)', label: 'SLE (Le)' },
  { value: 'SOS - Somali Shilling (Sh.So.)', label: 'SOS (Sh.So.)' },
  { value: 'SRD - Surinamese Dollar (SRD$)', label: 'SRD (SRD$)' },
  { value: 'SYP - Syrian Pound (£S)', label: 'SYP (£S)' },
  { value: 'SZL - Swazi Lilangeni (L)', label: 'SZL (L)' },
  { value: 'THB - Thai Baht (฿)', label: 'THB (฿)' },
  { value: 'TJS - Tajikistani Somoni (ЅМ)', label: 'TJS (ЅМ)' },
  { value: 'TMT - Turkmenistani Manat (T)', label: 'TMT (T)' },
  { value: 'TND - Tunisian Dinar (د.ت)', label: 'TND (د.ت)' },
  { value: "TOP - Tongan Pa'anga (T$)", label: 'TOP (T$)' },
  { value: 'TRY - Turkish Lira (₺)', label: 'TRY (₺)' },
  { value: 'TTD - Trinidad and Tobago Dollar (TT$)', label: 'TTD (TT$)' },
  { value: 'TWD - New Taiwan Dollar (NT$)', label: 'TWD (NT$)' },
  { value: 'TZS - Tanzanian Shilling (TSh)', label: 'TZS (TSh)' },
  { value: 'UAH - Ukrainian Hryvnia (₴)', label: 'UAH (₴)' },
  { value: 'UGX - Ugandan Shilling (USh)', label: 'UGX (USh)' },
  { value: 'USD - United States Dollar ($)', label: 'USD ($)' },
  { value: 'UYU - Uruguayan Peso ($U)', label: 'UYU ($U)' },
  { value: "UZS - Uzbekistan Som (so'm)", label: "UZS (so'm)" },
  { value: 'VND - Vietnamese Dong (₫)', label: 'VND (₫)' },
  { value: 'VUV - Vanuatu Vatu (VT)', label: 'VUV (VT)' },
  { value: 'WST - Samoan Tala (WS$)', label: 'WST (WS$)' },
  { value: 'XAF - Central African CFA Franc (FCFA)', label: 'XAF (FCFA)' },
  { value: 'XCD - East Caribbean Dollar (EC$)', label: 'XCD (EC$)' },
  { value: 'XOF - West African CFA Franc (CFA)', label: 'XOF (CFA)' },
  { value: 'XPF - CFP Franc (₣)', label: 'XPF (₣)' },
  { value: 'YER - Yemeni Rial (﷼)', label: 'YER (﷼)' },
  { value: 'ZAR - South African Rand (R)', label: 'ZAR (R)' },
  { value: 'ZMW - Zambian Kwacha (ZK)', label: 'ZMW (ZK)' },
];

// const extractedCurrency = currency.map((item) => {
//   const code = item.value.split("(")[1];
//   const newCode = code.replace(")", "");
//   console.log(newCode);
//   return {
//     label: c(ode,)
//   };
// });

// console.log(extractedCurrency);
