# Generated by Django 5.0 on 2024-02-28 16:17

import django.db.models.deletion
import employer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to=employer.models.company_logo)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(default='None', max_length=100)),
                ('company_type', models.CharField(default='None', max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('ntn', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_number', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_since', models.CharField(blank=True, max_length=50, null=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company_Info',
                'verbose_name_plural': 'Companies_Info',
                'db_table': 'Company_Info',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('hiring_number', models.CharField(blank=True, max_length=100, null=True)),
                ('hiring_country', models.CharField(blank=True, max_length=50, null=True)),
                ('hiring_state', models.CharField(blank=True, max_length=50, null=True)),
                ('hiring_city', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='Approved', max_length=50, null=True)),
                ('phase', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_start_range', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_end_range', models.CharField(blank=True, max_length=50, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('hiring_timeline', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('hide_company', models.BooleanField(blank=True, default=False, null=True)),
                ('skills', models.CharField(blank=True, max_length=150, null=True)),
                ('experience', models.CharField(blank=True, max_length=150, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Job_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('shortlisted_candidate', models.CharField(blank=True, max_length=50, null=True)),
                ('interview_candidate', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobs')),
            ],
            options={
                'verbose_name': 'Job_Reviews',
                'verbose_name_plural': 'Jobs_Reviews',
                'db_table': 'Jobs_Reviews',
            },
        ),
        migrations.CreateModel(
            name='EmployerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_status', models.BooleanField(default=True)),
                ('seeker', models.JSONField()),
                ('resume', models.FileField(blank=True, upload_to=employer.models.job_applicant_resume)),
                ('prescreen', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shortlist', 'Shortlist'), ('Interview', 'Interview'), ('Reject', 'Reject')], default='Pending', max_length=50, null=True)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('job_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employer.jobs')),
            ],
            options={
                'verbose_name': 'Employer Application',
                'verbose_name_plural': 'Employer Applications',
                'db_table': 'EmployerApplication',
            },
        ),
        migrations.CreateModel(
            name='Notes_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Todo_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'db_table': 'Todos',
            },
        ),
    ]
