# Generated by Django 5.0.2 on 2024-03-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_jobs_salary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
