# Generated by Django 5.0 on 2024-02-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='temp',
        ),
    ]
