# Generated by Django 5.0.2 on 2024-03-06 15:56

import backend.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_notification_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=backend.models.blog_image_upload_to)),
                ('description', models.JSONField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='resumetemplates',
            old_name='template_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='resumetemplates',
            name='template_html',
        ),
        migrations.AddField(
            model_name='resumetemplates',
            name='html_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage('C:\\Users\\kaj\\Desktop\\website\\PandaPlacement\\templates'), upload_to=backend.models.resume_template_html),
        ),
    ]
