# Generated by Django 5.0.2 on 2024-03-07 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_blog_rename_template_image_resumetemplates_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='resumetemplates',
            name='temID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
