# Generated by Django 4.2.11 on 2024-03-19 21:49

import backend.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplates',
            name='html_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage('/home/PandaPlacement/templates'), upload_to=backend.models.resume_template_html),
        ),
    ]
