# Generated by Django 5.0.2 on 2024-03-30 19:35

import backend.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_resumetemplates_html_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
    ]
