# Generated by Django 5.0.2 on 2024-05-13 20:05

import backend.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_resumetemplates_html_file_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplates',
            name='html_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage('C:\\KajDev\\panda-placement-apps\\gateway\\templates'), upload_to=backend.models.resume_template_html),
        ),
    ]
